class VisualizerTypes:
    COLORPLOTVISUALISATION1 = 'cpv1'
    CHANGESPERSESSION = 'ccps'
    TIMEBASEDVISUALIZER = 'tbv'
    TIMEBASEDCLUSERING = 'tbc'
    CONVOLUTIOCLUSTERING = 'cvc'
    EVENTPATTERNEXTRACTOR = 'evpe'